Accept=Onartu
Close=Itxi

Price= Prezioa
SelectOption=Aukeratu


MainGUI.CreateRide= Bidaia sortu
MainGUI.QueryRides= Bidaiak kontsultatu
MainGUI.SelectOption=Aukeratu
MainGUI.MainTitle=Bidaiak
MainGUI.Login=Saioa hasi
MainGUI.Erregistratu=Erregistratu

CreateRideGUI.LeavingFrom=Nondik
CreateRideGUI.GoingTo=Nora
CreateRideGUI.RideDate=Bidaia eguna
CreateRideGUI.Rides=Bidaiak
CreateRideGUI.NumberOfSeats=Eserleku kopurua
CreateRideGUI.SeatsMustBeGreaterThan0=ERROR, eserleku kopurua 0 baino handiagoa
CreateRideGUI.PriceMustBeGreaterThan0=ERROR, prezioa 0 baino handiagoa

CreateRideGUI.ErrorRideMustBeLaterThanToday=ERROR, bidaia gaur baino beranduago
CreateRideGUI.RideCreated=Bidaia sortuta
CreateRideGUI.CreateRide=Bidaia sortu
CreateRideGUI.Price=Prezioa
CreateRideGUI.ErrorNumber=Error, prezioa eta eserlekuak zenbaki bat izan behar dira

CreateRideGUI.ErrorQuery=Error, datuak falta dira
CreateRideGUI.AsegurarViaje=Bidaia aseguratu (2\u20AC)
CreateRideGUI.NoDineroSufi=Ez duzu diru nahikorik bidaia hau aseguratzeko


FindRidesGUI.NoRides=Ez daude bidaiak
FindRidesGUI.Driver=Gidaria
FindRidesGUI.CalificacionMedia=Bataz besteko kalifikazioa
FindRidesGUI.NPlaces=Eserlekuak
FindRidesGUI.Price=Prezioa
FindRidesGUI.FindRides=Bidaiak bilatu
FindRidesGUI.Rides=Bidaiak
FindRidesGUI.Rides=Bidaia
FindRidesGUI.Erreserbatu=Reservar


DataAccess.RideAlreadyExist=ERROR, Bidaia existizen da

RegisterGUI.this.title=Erregistratu
RegisterGUI.UserName=Erabiltzailea
RegisterGUI.Password=Pasahitza
RegisterGUI.Mail=Posta Elektronikoa 
RegisterGUI.PhoneNumber=Telefono zenbakia
RegisterGUI.Driver=Gidaria
RegisterGUI.Traveler=Bidaiaria
RegisterGUI.Register=Erregistratu
RegisterGUI.Error=Erabiltzailea existitzen da
RegisterGUI.Done=Erregistratuta
RegisterGUI.Money =Dirua

RateGUI.done = Kalifikatuta
RateGUI.error = Kalifikazioa ezeztatuta


LoginGUI.this.title=Saioa hasi
LoginGUI.UserName=Erabiltzailea
LoginGUI.Password=Pasahitza
LoginGUI.Login=Hasi saioa
LoginGUI.Error=Errorea


MoneyGUI.this.title=Diru kudeaketa
MoneyGUI.Saldo=Kontuko saldoa:
MoneyGUI.Deposit=Sartu
MoneyGUI.Withdraw=Atera
MoneyGUI.EzNaturala=ERROREA, Zenbaki natural bat sartu (0,1,2...)
MoneyGUI.Big=ERROR, Saldo bahiano diru gehiago ataratzen saiatu


DriverGUI.this.title=Gidaria
DriverGUI.Konfirmatu=Erreserba baieztatu
DriverGUI.DarseBaja = Baja eman
DriverGUI.GestionarMonedero = Diru Kudeaketa

TravelerGUI.title=Bidaiaria
TravelerGUI.Erreserba = Erreserbatu
TravelerGUI.Cancelar = Ezeztatu
TravelerGUI.Calificar = Kalifikatu
TravelerGUI.DarseBaja = Baja eman
TravelerGUi.GestionarMonedero = Diru Kudeaketa


UserGUI.Money=Diru kudeaketa

BookRideGUI.title=Bidaiaren erreserba
BookRideGUI.OharraTitle=Oharra
BookRideGUI.EserlekuTitle=Eserleku kopurua
BookRideGUI.Irteera=Irteera
BookRideGUI.Helmuga=Helmuga
BookRideGUI.Data=Data
BookRideGUI.PrezioaTitle=Prezioa (\u20AC)
BookRideGUI.Erreserbatu=Erreserbatu
BookRideGUI.gordeDa=Erreserba zuzen sortu da
BookRideGUI.EzDaGorde=Erreserba ezin izan da sortu
BookRideGUI.pendiente=Erreserba eskatu da. Gidariaren berrespena itxaroten.
BookRideGUI.NoDineroSufi = Ez daukezu bidai honetarako diru nahikoa
BookRideGUI.Descuento = Bidaia horretan %50eko deskontua duzu!

GestionarMonederoGUI.Label = Sartu diru kantitatea
GestionarMonederoGUI.Guardar = Gorde
GestionarMonederoGUI.Ingresar = Sartu
GestionarMonederoGUI.Extraer = Atera
GestionarMonederoGUI.Close = Itxi
GestionarMonederoGUI.NoDineroSufi = Ez daukazu diru nahikorik
GestionarMonederoGUI.OperacionCorrecta = Eragiketa Zuzena
GestionarMonederoGUI.OperacionIncorrecta = Eragiketa Okerra
GestionarMonederoGUI.Titulo = Zure eragiketa aukeratu
GestionarMonederoGUI.Dinero = Dirua

PagoGUI.NombreTitular = Titularraren izena
PagoGUI.NumeroCuenta = Txartel zenbakia
PagoGUI.FechaCaducidad = Iraungitze-data
PagoGUI.CVV = CVV
PagoGUI.PagoRealizado = Ordainketa Zuzena
PagoGUI.NoValido = Informazioa ez da egokia
PagoGUI.Close = Itxi

DarseBajaGUI.Baja = Baja eman
DarseBajaGUI.Correcto = Baja zuzenki emana
DarseBajaGUI.Error = Informazioa ez da zuzena
DarseBajaGUI.Close = Itxi

OnartuGUI.title=Erreserba baieztatu
OnartuGUI.Onartu=Onartu
OnartuGUI.Deuseztatu=Deuseztatu